apiVersion: apps/v1v1 
kind: Deployment
metadata: 
  name: app1 
  labels: 
    app: app1 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1 
  template:
    metadata:
      labels: 
        app: app1 
    spec: 
      containers: 
      - nanme: app1 
        image: rakeshreddy07/app1:1.0.0
        ports: 
        - containerPort: 80 
---
kind: Service
apiVersion: v1 
metadata:
  name: nginx 
spec:
  selector:
  app: app1 
ports: 
- protocol: TCP 
  port: 80
  targetPort: 80 

