apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app1 
  labels: 
    app: app1 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1 
  template:
    metadata:
      labels: 
        app: app1 
    spec: 
      containers: 
      - name: app1 
        image: rakeshreddy07/app1:1.0.0
        ports: 
        - containerPort: 80 
---
kind: Service
apiVersion: v1 
metadata:
  name: app1  
spec:
  selector:
    app: app1 
  ports: 
  - protocol: TCP 
    port: 80
    targetPort: 80 

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:361769572747:certificate/b9e0d09c-69a9-4ad2-b20e-9a631b15e4b6
    alb.ingress.kubernetes.io/group.name: joindevops
spec:
  ingressClassName: alb
  rules:
  - host: "app1.devopsaws82s.online"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app1
            port:
              number: 80